barrierfree/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('users.urls')),
    
    path('accounts/', include('allauth.urls')),
    
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views
# import reply.views
from django.conf.urls.static import static
from django.conf import settings

app_name = "blog"

urlpatterns = [
    path('', views.blog_view, name="blog"),

    path('<int:post_id>/', views.blogdt_view, name='blogdt'),

    path('create/', views.create, name="create"),
    path('delete/<int:post_id>', views.delete, name="delete"),
    path('edit/<int:post_id>', views.edit, name="edit"),

    path('comment/create/<int:post_id>', views.create),    
    path('comment/delete/<int:post_id>/<int:com_id>', views.delete_comment, name="delete_comment"),    
    path('comment/edit/<int:post_id>/<int:com_id>', views.edit_comment, name="edit_comment"),
    
    path('download/<int:post_id>/', views.download_file, name='download_file'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
# import reply.views

app_name = "user"

urlpatterns = [
    path('', views.index_view, name="index"),

    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup"),    
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    path('password_reset/', views.password_reset_request, name="password_reset"),

    path('upload/', views.upload_view, name="upload"),

    path('blog/', include('blog.urls')),

    # path('blog/', views.blog_view, name="blog"),    
    # path('blog/<int:post_id>/', views.blogdt_view, name='blogdt'),
    
    # path('create/', views.create, name="create"),       
    # path('download/<int:post_id>/', views.download_file, name='download_file'),
    
    # path('reply/create/<int:post_id>', reply.views.create),    
    # path('delete/comment/<int:post_id>/<int:com_id>', views.delete_comment, name="delete_comment"),    
    # path('edit/comment/<int:post_id>/<int:com_id>', views.edit_comment, name="edit_comment"),
    # path('delete/<int:post_id>', views.delete, name="delete"),
    # path('edit/<int:post_id>', views.edit, name="edit"),
    
    path('withdraw/', views.withdraw, name="withdraw"),
    path('mypage/<int:id>/', views.mypage_view, name="mypage"),
    path('mypage/update/<int:id>/', views.mypage_update, name="mypage_update"),
    path('mypage/update/password/<int:id>/', views.new_password, name="new_password"),
    path('mypage/my_post', views.my_post, name="my_post"),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
from users.models import User
# Create your models here.    
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    file = models.FileField(upload_to='post_files/')
    language = models.CharField(max_length=10)
    
    def __str__(self):
        return self.title
    
    def get_filename(self):
        return os.path.basename(self.file.name)
    
class Reply(models.Model):
    contents = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-id']

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=10)
    
# class Post(models.Model):
#     title = models.CharField(max_length=100)
#     content = models.TextField()
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     date = models.DateField(auto_now_add=True)
#     view_count = models.PositiveIntegerField(default=0)
#     file = models.FileField(upload_to='post_files/')
#     language = models.CharField(max_length=10)
    
#     def __str__(self):
#         return self.title
    
#     def get_filename(self):
#         return os.path.basename(self.file.name)
    
class Video(models.Model):
    file = models.FileField(upload_to='temp_video/')
    
    def get_filename(self):
        return os.path.basename(self.file.name)
    
    def get_file_path(self):
        return os.path.abspath(self.file.path)

blog/forms.py
from django import forms
from .models import Post, Reply

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if user:
            self.initial['author'] = user.id
            self.fields['author'].widget = forms.HiddenInput()

        # Modify CSS classes for form fields
        self.fields['title'].widget.attrs['class'] = 'form-control my-input'
        self.fields['content'].widget.attrs['class'] = 'form-control my-textarea'
        self.fields['file'].widget.attrs['class'] = 'form-control my-file-input'

    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'file', 'language']
        labels = {
            'title': '제목',
            'content': '내용',
            'file': '파일',
        }

class ReplyForm(forms.ModelForm):            
    class Meta:
        model = Reply
        fields = ('contents', 'author')
        exclude = ('author',)

users/forms.py
from django import forms
# from .models import Post

# class PostForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         user = kwargs.pop('user', None)
#         super(PostForm, self).__init__(*args, **kwargs)
#         if user:
#             self.initial['author'] = user.id
#             self.fields['author'].widget = forms.HiddenInput()

#         # Modify CSS classes for form fields
#         self.fields['title'].widget.attrs['class'] = 'form-control my-input'
#         self.fields['content'].widget.attrs['class'] = 'form-control my-textarea'
#         self.fields['file'].widget.attrs['class'] = 'form-control my-file-input'

#     class Meta:
#         model = Post
#         fields = ['title', 'content', 'author', 'file', 'language']
#         labels = {
#             'title': '제목',
#             'content': '내용',
#             'file': '파일',
#         }
        
class VideoForm(forms.Form):
    file = forms.FileField()

blog/views.py
from django.http import FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

import datetime
from datetime import timedelta

from .models import Post, Reply
from .forms import PostForm, ReplyForm

# from reply.models import Reply
# from reply.forms import ReplyForm

# Create your views here.
@login_required(login_url='user:index')
def blog_view(request):
    postlist = Post.objects.all()
    paginator = Paginator(postlist, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:blog')
    else:
        form = PostForm()
    return render(request, 'blog.html', {'posts':posts, 'form': form})

@login_required(login_url='/')
def blogdt_view(request, post_id):
    post = Post.objects.prefetch_related('reply_set').get(id=post_id)
    replyForm = ReplyForm()
    response = render(request, 'blog-details.html', {'post':post, 'replyForm':replyForm})
    
    expire_date, now = datetime.datetime.now(), datetime.datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()
    
    cookie_value = request.COOKIES.get('hitblog', '_')

    if f'_{post_id}_' not in cookie_value:
        cookie_value += f'{post_id}_'
        response.set_cookie('hitblog', value=cookie_value, max_age=max_age, httponly=True)
        post.view_count += 1
        post.save()
    return response

@login_required(login_url='/') 
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.author_id = request.user.id  # Set the author ID
            post.save()
            return redirect('blog:blog')
    else:
        form = PostForm(user=request.user)
    return render(request, 'create.html', {'form': form})

@login_required(login_url='/')
def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('blog:blog')

@login_required(login_url='/')
def edit(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == "POST":
        postForm = PostForm(request.POST, request.FILES, instance=post)
        if postForm.is_valid():
            postForm.save()
            return redirect('blog:blogdt', post_id)
    else:
        postForm = PostForm(instance=post, initial={
            'title': post.title,
            'content': post.content,
            'file': post.file,
        })
        postForm.fields['file'].required = False
    return render(request, 'change_create.html', {'form':postForm, 'post':post})

def download_file(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    file_path = post.file.path
    return FileResponse(open(file_path, 'rb'), as_attachment=True)

@login_required(login_url='/')
def delete_comment(request, post_id, com_id):
    my_com = Reply.objects.get(id=com_id)
    my_com.delete()
    return redirect('/blog/'+str(post_id))

@login_required(login_url='/')
def edit_comment(request, post_id, com_id):
    post = Post.objects.prefetch_related('reply_set').get(id=post_id)
    comment = get_object_or_404(Reply, id=com_id)
    if request.method == "POST":
        replyForm = ReplyForm(request.POST, instance=comment)
        if replyForm.is_valid():
            comment = replyForm.save()
            return redirect('blog:blogdt', post_id)
    else:
        replyForm = ReplyForm(instance=comment)
    return render(request, 'comment_edit.html', {'post':post, 'comment':comment})

users/templates/activation_email.html
{% autoescape off %}
    안녕하세요 눈으로 듣는 배리어프리 서비스에 오신걸 환영합니다!

    아래 링크를 클릭하면 회원가입 인증이 완료됩니다.

    회원가입 링크 : {{ domain }}{% url 'user:activate' uidb64=uid token=token %}

{% endautoescape %}

users/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    {% comment %} {% include 'head.html' %} {% endcomment %}
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

users/templates/blog-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'test/dthead.html' %}
<link href="{% static 'css/blogdt.css' %}" rel="stylesheet">
<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <h1>눈으로 듣는 배리어프리<br> 자막 서비스<span>!</span></h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/#hero">홈</a></li>
          <li><a href="/#about">정보</a></li>
          <li><a href="/#team">팀원</a></li>
          <li><a href="{% url 'user:blog' %}">자막 게시판</a></li>
          <li><a href="{% url 'user:upload' %}">자막 생성</a></li>
            {% if user.is_authenticated %}
            <li class="dropdown"><a href="#"><span>{% if user.nickname %}{{ user.nickname }}{% else %}{{ user.username }}{% endif %}</span> <i class="bi bi-person-circle"></i></a>
              <ul>
                <li><a href="{% url 'user:mypage' user.id %}">내정보</a></li>
                <li><a href="#">내가 쓴 글</a></li>
                <li><a href="{% url 'user:logout' %}">로그아웃</a></li>
              </ul>
            </li>
            {% else %}
            <li><a href="" class="js-activation-button">로그인</a></li>
            {% endif %}
        </ul>
      </nav><!-- .navbar -->
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>
  </header><!-- End Header -->
  <!-- End Header -->

  <main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>게시판</h2>
              <p>여기서 자막을 공유하거나 다운로드 할 수 있습니다!</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'user:index' %}">홈</a></li>
            <li>자막 공유 게시판</li>
            <li class="active">자막 공유 게시판 내용<li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Blog Details Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row g-5">

          <div class="col-lg-12">

            <article class="blog-details">
              <h2 class="title">{{post.title}}</h2>
              <div class="meta-top">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="">{{post.author}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="{{post.date|date:'Y-m-d'}}">{{post.date|date:'Y년 m월 d일'}}</time></li>

                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href=""> 댓글 </a></li>
                  <hr>
                  <li class="d-flex align-items-center"><i class="bi bi-file-earmark-arrow-down"></i> <a href="{% url 'user:download_file' post_id=post.id %}">{{ post.get_filename }}</a></li>
                  <hr>
                </ul>
              </div><!-- End meta top -->

              <div class="content">
                <p>
                  {{ post.content }}
                </p>
              </div><!-- End post content -->
            </article><!-- End blog post -->
            <div class="button-group mt-4">
              <button onclick="history.go(-1);" class="btn btn-primary float-end">뒤로가기</button>
              {% if user.is_authenticated and user == post.author %}
              <button onclick="window.location.href='{% url 'user:delete' post.id %}'"class="btn btn-danger float-end me-2">삭제</button>
              <button onclick="window.location.href='{% url 'user:edit' post.id %}'" class="btn btn-primary float-end me-2">수정</button>
              {% endif %}
            </div>


            {% if post.reply_set %}
            <div class="comments">
              <h4 class="comments-count">댓글</h4>
              {% for reply in post.reply_set.all %}
              <div id="comment-1" class="comment">
                <div class="d-flex">
                  <div>
                    <div class="comment-bubble">
                      <h5><a href="">{{ reply.author }}</a></h5>
                      <time datetime="{{ reply.create_date|date:'Y-m-d H:i' }}">{{ reply.create_date|date:'Y년 m월 d일 H시i분' }}</time>
                      <hr>
                      <p>
                        {{ reply.contents }}
                      </p>
                      <hr>
                      <p class="comment-actions">
                        {% if user.is_authenticated and user == reply.author %}
                        <button onclick="window.location.href='{% url 'user:edit_comment' post.id reply.id  %}'" class="btn btn-sm btn-primary edit-reply-btn">수정</button>
                        <button onclick="window.location.href='{% url 'user:delete_comment' post.id reply.id  %}'" class="btn btn-sm btn-danger delete-reply-btn">삭제</button>
                        {% endif %}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            {% endif %}
            
            
            <div class="reply-form mt-3">
              <h4>댓글 남기기</h4>
              {% comment %} <p> * </p> {% endcomment %}
              <form action="/reply/create/{{ post.id }}" method="POST">
                {% csrf_token %}
                {% comment %} {{ replyForm }} {% endcomment %}
                <div class="row">
                  <div class="col form-group">
                    <textarea name="contents" class="form-control" placeholder="여기에 댓글을 남겨주세요!*" required></textarea>
                  </div>
                </div>
                <input type="hidden" name="author" value="{{ request.user.id }}">
                <button type="submit" class="btn btn-primary mt-2">작성</button>
              </form>
            </div>

    </section><!-- End Blog Details Section -->
      
  </main><!-- End #main -->
  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>
  <script src="{% static 'js/blogdt.js' %}"></script>
  {% include 'test/dtscript.html' %}
  {% include 'test/footer.html' %}  
</body>
</html>

users/templates/create.html
{% load static %}
<html lang="ko">
{% include 'test/head.html' %}
<link rel="stylesheet" href="{% static 'css/blog_create.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
            <a href="{% url 'user:index' %}" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1>눈으로 듣는 배리어프리<br> 자막 서비스<span>!</span></h1>
            </a>
            <nav id="navbar" class="navbar">
                <ul>
                  <li><a href="/#hero">홈</a></li>
                  <li><a href="/#about">정보</a></li>
                  <li><a href="/#team">팀원</a></li>
                  <li><a href="/blog">자막 게시판</a></li>
                  <li><a href="{% url 'user:upload' %}">자막 생성</a></li>
                  {% if user.is_authenticated %}
                    <li class="dropdown">
                      <a href="#"><span>{% if user.nickname %}{{ user.nickname }}{% else %}{{ user.username }}{% endif %}</span> <i class="bi bi-person-circle"></i></a>
                      <ul>
                        <li><a href="{% url 'user:mypage' user.id %}">내정보</a></li>
                        <li><a href="{% url 'user:my_post' %}">내가 쓴 글</a></li>
                        <li><a href="{% url 'user:logout' %}">로그아웃</a></li>
                      </ul>
                    </li>
                  {% else %}
                    <li><a href="" class="js-activation-button">로그인</a></li>
                  {% endif %}
                </ul>
              </nav><!-- .navbar -->
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
        </div>
    </header><!-- End Header -->

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <div class="page-header d-flex align-items-center" style="background-image: url('');">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>게시글 작성</h2>
                        <p>생성된 자막을 공유를 위해 게시글 작성 공간!</p>
                    </div>
                </div>
            </div>
        </div>
        <nav>
            <div class="container">
                <ol>
                    <li><a href="index.html">홈</a></li>
                    <li><a href="">게시글</a><li>
                    <li>게시글 작성</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Breadcrumbs -->
    
    <div class="container_blog mt-3 mb-3">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_title" class="form-label">제목</label>
                <input type="text" class="my-input" id="id_title" name="title" placeholder="제목을 입력해주세요" required>
            </div>
            <hr class="my-hr">
            
            <div class="mb-3">
                <label for="id_content" class="form-label">내용</label>
                <textarea class="my-textarea" id="id_content" name="content" rows="5" placeholder="내용을 입력해주세요" required></textarea>
            </div>
            <hr class="my-hr">
            
            <div class="mb-3">
                <label for="id_file" class="form-label">파일 업로드</label>
                <input type="file" class="my-file-input" id="id_file" name="file" accept=".vtt" required>
            </div>
            <hr class="my-hr">
            
            <div class="language-selection">
                <p>자막 언어 선택</p>
                <input type="radio" id="ko" name="language" value="ko" checked>
                <label for="ko" class="language-button">ko</label>
                <input type="radio" id="en" name="language" value="en">
                <label for="en" class="language-button">en</label>
            </div>
            <hr class="my-hr">
            
            <div class="button-container">
                <input type="hidden" name="author" value="{{ request.user.id }}">
                <button type="submit" class="btn btn-primary btn-custom">작성</button>
                <button type="button" class="btn btn-danger btn-custom ms-2" data-bs-toggle="modal" data-bs-target="#confirmModal">나가기</button>
            </div>           
        </form>
    </div>
    <!-- 확인용 Modal -->
    <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmModalLabel">게시글 작성 취소</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 작성을 취소 하시겠습니까?
                </div>  
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">돌아가기</button>
                    <button type="button" class="btn btn-danger" onclick="window.location.href='/blog'">네</button>
                </div>
            </div>
        </div>
    </div>

    <!-- JS Files -->
    {% include 'test/script.html' %}
    {% include 'test/footer.html' %}
    <link href="{% static '/js/blog_create.css' %}">
    <script>
        document.getElementById('id_file').addEventListener('change', function() {
            var fileInput = document.getElementById('id_file');
            var filePath = fileInput.value;
            var allowedExtensions = /(\.vtt)$/i; // 허용된 확장자 패턴을 정의
    
            if (!allowedExtensions.exec(filePath)) {
                alert('자막 파일(.vtt)만 업로드 가능합니다.');
                fileInput.value = ''; // 파일 선택 초기화
            }
        });


        document.getElementById('id_title').addEventListener('blur', function() {
            var titleInput = document.getElementById('id_title');
            var titleValue = titleInput.value;
            var numberRegex = /^[0-9]+$/; // 숫자만 있는지 확인하는 정규식 패턴
    
            if (numberRegex.test(titleValue)) {
                alert('올바른 제목을 입력해주세요.');
                titleInput.value = ''; // 제목 입력 초기화
            }
        });
    </script>    
</body>
</html>

users/templates/edit.html
<form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col form-group">
        <textarea name="contents" class="form-control" placeholder="여기에 댓글을 남겨주세요!*" required></textarea>
      </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">작성</button>
</form>

users/templates/password_reset.html
{% load static %}
{% include 'test/head.html' %}
<body>
    <!--Reset Password-->
    <div>
        <h2>비밀번호 재설정</h2>
      <hr>
      <p>비밀번호를 잊어버리셨나요?<br>
            가입하신 이메일을 입력해 주세요.<br>
            잠시 후 해당 이메일로 비밀번호 재설정 메일이 발송됩니다.</p>
          <form method="POST">
              {% csrf_token %}
              {{ password_reset_form }}
              <button type="submit">전송</button>
          </form>
      </div>
      {% include 'test/script.html' %}
      {% include 'test/footer.html' %}
</body>

users/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

    <div>
	    <h2>패스워드 변경 완료</h2>
		<hr>
        <p>패스워드 변경이 완료되었습니다. 다시 로그인 해주세요.</p>
    </div>

{% endblock %}

users/templates/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

  <!--Password Reset Confirm-->
    <div>
	    <h2>비밀번호 재설정</h2>
		<hr>
        <p>새 비밀번호를 입력해 주세요.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button>저장</button>
        </form>
    </div>

{% endblock %}

users/templates/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

	<!--Password reset sent-->
	<div>
  		<h2>비밀번호 재설정 메일 발송 완료</h2>
		<hr>
		<p>
			비밀번호 재설정을 위한 메일이 발송되었습니다.<br>
			30분 내에 비밀번호를 재설정 해주세요.<br>
			만약 메일이 오지 않는다면, 이메일 주소를 다시 한번 확인해 주시고, 스팸 폴더를 확인해 주세요.
		</p>
  </div>

{% endblock %}